- name: Create alloy working directory
  ansible.builtin.file:
    path: "{{ alloy_working_dir }}"
    state: directory
    owner: "{{ alloy_service_user }}"
    group: "{{ alloy_service_group }}"
    mode: "0755"
  become: true

- name: Create alloy config directory
  ansible.builtin.file:
    path: "{{ alloy_config_dir }}"
    state: directory
    owner: "{{ alloy_service_user }}"
    group: "{{ alloy_service_group }}"
    mode: '0755'
  become: true

- name: Create systemd service unit
  ansible.builtin.template:
    src: "{{ alloy_service_name }}.service.j2"
    dest: /etc/systemd/system/{{ alloy_service_name }}.service
    owner: root
    group: root
    mode: 0644
  become: true

- name: Deploy alloy configuration file
  ansible.builtin.template:
    src: config.alloy.j2
    dest: "{{ alloy_config_dir }}/{{ alloy_config_file }}"
    owner: "{{ alloy_service_user }}"
    group: "{{ alloy_service_group }}"
    mode: '0644'
  notify: Restart Alloy
  become: true

- name: Deploy alloy env file
  ansible.builtin.template:
    src: "{{ alloy_environment_file }}.j2"
    dest: "{{ alloy_config_dir }}/{{ alloy_environment_file }}"
    owner: "{{ alloy_service_user }}"
    group: "{{ alloy_service_group }}"
    mode: '0644'
  notify: Restart Alloy
  become: true
