- name: Create alloy group
  ansible.builtin.group:
    name: "{{ alloy_service_group }}"
    system: true
  become: true

- name: Create alloy user
  ansible.builtin.user:
    name: "{{ alloy_service_user }}"
    groups: "{{ [ alloy_service_group ] + alloy_user_groups }}"
    system: true
    create_home: false  # Appropriate for a system user, usually doesn't need a home directory
  become: true

- name: Get binary
  block:
    - name: Ensure working path exists
      ansible.builtin.file:
        path: "{{ alloy_archive_path }}"
        state: directory
        owner: "{{ alloy_service_user }}"
        group: "{{ alloy_service_group }}"
        mode: "0755"

    - name: Unpack binary
      become: false
      ansible.builtin.unarchive:
        src: "v{{ alloy_version }}/alloy-linux-{{ go_arch }}.zip"
        dest: "{{ alloy_archive_path }}"
        mode: 0755
      check_mode: false

    - name: Propagate locally distributed binaries
      ansible.builtin.copy:
        src: "{{ alloy_archive_path }}/alloy-linux-{{ go_arch }}"
        dest: "{{ alloy_binary_dir }}/alloy"
        mode: 0755
        owner: "{{ alloy_service_user }}"
        group: "{{ alloy_service_group }}"
