---
# legacy config
- name: Create/Delete/Update alert notifications channels (provisioning)
  ansible.builtin.copy:
    content: |
      apiVersion: 1
      {{ grafana_alert_notifications | to_nice_yaml }}
    dest: /etc/grafana/provisioning/notification/ansible.yml
    owner: "{{ grafana_service_user }}"
    group: "{{ grafana_service_group }}"
    mode: 0640
  become: true
  notify: Restart Grafana
  when: grafana_use_provisioning and grafana_alert_notifications | length > 0

# new alert resources
- name: Create/Delete/Update alert resources (provisioning)
  ansible.builtin.copy:
    content: |
      apiVersion: 1
      {{ grafana_alert_resources | to_nice_yaml }}
    dest: /etc/grafana/provisioning/alerting/ansible.yml
    owner: "{{ grafana_service_user }}"
    group: "{{ grafana_service_Group }}"
    mode: 0640
  become: true
  notify: Restart Grafana
  when: grafana_use_provisioning and grafana_alert_resources | length > 0
