---
- name: Reload systemd daemon to pick up changes
  ansible.builtin.systemd:
    daemon_reload: yes
  become: true

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Enable and start Grafana systemd unit
  ansible.builtin.systemd:
    name: "{{ grafana_service_name }}"
    enabled: true
    state: started
    daemon_reload: true
  become: true