---
- name: Create Mimir group
  ansible.builtin.group:
    name: "{{ mimir_service_group }}"
    system: true
  become: true

- name: Create Mimir user
  ansible.builtin.user:
    name: "{{ mimir_service_user }}"
    groups: "{{ [ mimir_service_group ] + mimir_user_groups }}"
    system: true
    create_home: false  # Appropriate for a system user, usually doesn't need a home directory
  become: true

- name: Download Mimir package
  ansible.builtin.copy:
    src: "{{ mimir_package_path }}"
    dest: "/tmp/{{ mimir_package }}"
    mode: '0755'
  become: true

- name: DNF - Install Mimir
  ansible.builtin.dnf:
    name: "/tmp/{{ mimir_package }}"
    state: present
    disable_gpg_check: true
  notify: Restart Mimir
  when: ansible_os_family in ['RedHat', 'Rocky']

- name: APT - Install Mimir
  ansible.builtin.apt:
    deb: "/tmp/{{ mimir_package }}"
    state: present
  notify: Restart Mimir
  when: ansible_os_family == 'Debian'
