---
- name: Install Mimir
  include_tasks: install.yml
  tags: [install]

- name: Configure Mimir
  include_tasks: configure.yml
  tags: [configure]

- name: Manage Mimir service
  include_tasks: service.yml
  tags: [service]

- name: Uninstall Mimir service
  ansible.builtin.include_tasks:
    file: "uninstall.yml"
    apply:
      tags:
        - mimir_uninstall
        - never
  tags:
    - mimir_uninstall
    - never