---
- name: Reload systemd daemon to pick up changes
  ansible.builtin.systemd:
    daemon_reload: yes
  become: true

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Ensure Alertmanager service is enabled and running
  ansible.builtin.service:
    name: "{{ alertmanager_service_name }}"
    enabled: yes
    state: started
  become: true

