---
scenario:
  name: default
driver:
  name: docker
platforms:
#  - name: Ubuntu-22.04
#    image: geerlingguy/docker-ubuntu2204-ansible:latest
#    command: ${MOLECULE_DOCKER_COMMAND:-"/sbin/init"}
#    volumes:
#      - /sys/fs/cgroup:/sys/fs/cgroup:rw
#    cgroupns_mode: host
#    privileged: true
#    pre_build_image: true
  - name: RockyLinux-9
    image: geerlingguy/docker-rockylinux9-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-"/sbin/init"}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  log: true
  env:
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/roles
