---
- name: Ensure working path exists
  ansible.builtin.file:
    path: "{{ loki_working_path }}"
    state: directory
    owner: "{{ loki_service_user }}"
    group: "{{ loki_service_group }}"
    mode: "0755"

- name: Ensure config path exists
  ansible.builtin.file:
    path: "{{ loki_config_path }}"
    state: directory
    owner: "{{ loki_service_user }}"
    group: "{{ loki_service_group }}"
    mode: "0755"

- name: Create systemd service unit
  ansible.builtin.template:
    src: loki.service.j2
    dest: /etc/systemd/system/loki.service
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart Loki

- name: Template Loki config
  ansible.builtin.template:
    src: "config.yml.j2"
    dest: "{{ loki_config_path }}/config.yml"
    owner: "{{ loki_service_user }}"
    group: "{{ loki_service_group }}"
    mode: "0644"
    validate: "{{ loki_binnary_path }}/loki --verify-config -config.file %s"
  notify: Restart Loki

- name: Ensure that Loki rule path exists
  ansible.builtin.file:
    path: "{{ loki_ruler_alert_path }}"
    state: directory
    owner: "{{ loki_service_user }}"
    group: "{{ loki_service_group }}"
    mode: "0750"
  when:
    - loki_ruler_alert_path is defined
    - loki_ruler is defined

- name: Template Loki Rule File
  ansible.builtin.template:
    src: "rules.yml.j2"
    dest: "{{ loki_ruler_alert_path }}/rules.yml"
    owner: "{{ loki_service_user }}"
    group: "{{ loki_service_group }}"
    mode: "0644"
  notify: Restart Loki
  when:
    - loki_ruler_alerts is defined
    - loki_ruler_alert_path is defined
    - loki_ruler is defined

