---
- name: Ensure that Loki working path exists
  ansible.builtin.file:
    path: "{{ loki_working_path }}"
    state: directory
    owner: "{{ loki_service_user }}"
    group: "{{ loki_service_group }}"
    mode: "0755"

- name: Template Loki config - /etc/loki/config.yml
  ansible.builtin.template:
    src: "config.yml.j2"
    dest: "/etc/loki/config.yml"
    owner: "{{ loki_service_user }}"
    group: "{{ loki_service_group }}"
    mode: "0644"
    validate: "/usr/bin/loki --verify-config -config.file %s"
  notify: Restart Loki

- name: Ensure that Loki rule path exists
  ansible.builtin.file:
    path: "{{ loki_ruler_alert_path }}"
    state: directory
    owner: "{{ loki_service_user }}"
    group: "{{ loki_service_group }}"
    mode: "0750"
  when:
    - loki_ruler_alert_path is defined
    - loki_ruler is defined

- name: Template Loki Rule File
  ansible.builtin.template:
    src: "rules.yml.j2"
    dest: "{{ loki_ruler_alert_path }}/rules.yml"
    owner: "{{ loki_service_user }}"
    group: "{{ loki_service_group }}"
    mode: "0644"
  notify: Restart Loki
  when:
    - loki_ruler_alerts is defined
    - loki_ruler_alert_path is defined
    - loki_ruler is defined

