---
- name: Install Loki
  include_tasks: install.yml
  tags: [install]

- name: Configure Loki
  include_tasks: configure.yml
  tags: [configure]

- name: Manage Loki service
  include_tasks: service.yml
  tags: [service]

- name: Uninstall Loki service
  ansible.builtin.include_tasks:
    file: "uninstall.yml"
    apply:
      tags:
        - loki_uninstall
        - never
  tags:
    - loki_uninstall
    - never
