---
- name: Health check MinIO
  ansible.builtin.uri:
    url: "{{ minio_server_health_url }}"
    follow_redirects: none
    method: GET
  register: _result
  failed_when: false
  until: _result.status == 200
  retries: 5
  delay: 8
  changed_when: false
  when: not ansible_check_mode

- name: Check system logs if MinIO is not started
  when: not ansible_check_mode and _result.status != 200
  block:
    - name: Run journalctl
      ansible.builtin.shell:
        cmd: "journalctl -u {{ minio_service_name }} -b -n20 --no-pager"
      register: journal_ret
      changed_when: false
    - name: Output MinIO logs
      ansible.builtin.debug:
        var: journal_ret.stdout_lines
    - name: Raise alerts
      ansible.builtin.assert:
        that: false
        fail_msg: "Service {{ minio_service_name }} hasn't started."
