---
alertmanager_slack_api_url: http://slack.com/jmasnkdjfkas
alertmanager_receivers:
  - name: slack
    slack_configs:
      - send_resolved: true
        channel: '#alerts'
alertmanager_route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: slack
  # This routes performs a regular expression match on alert labels to
  # catch alerts that are related to a list of services.
  routes:
    - match_re:
        service: ^(foo1|foo2|baz)$
      receiver: slack
      # The service has a sub-route for critical alerts, any alerts
      # that do not match, i.e. severity != critical, fall-back to the
      # parent node and are sent to 'team-X-mails'
      routes:
        - match:
            severity: critical
          receiver: slack

